import streamlit as st
import ollama

def get_financial_advice(user_input):
   
    prompt = f"""
    You are a professional financial advisor specializing in stock market analysis.
    Analyze the following financial query and provide comprehensive advice:
    
    {user_input}
    
    Provide the result in the following structured format:
    
    1. Analysis Summary: [Brief summary of the query]
    2. Key Considerations: [3-5 bullet points of important factors]
    3. Technical Indicators (if applicable): [Relevant indicators like RSI, MACD, moving averages]
    4. Risk Assessment: [Low/Medium/High risk assessment]
    5. Potential Strategies: [1-3 suggested approaches]
    6. Recommended Actions: [Clear action items]
    7. Disclaimer: [Standard investment disclaimer]
    
    Only provide advice related to stocks, investing, or financial markets.
    If the question is not financial-related, politely decline to answer.
    """

    response = ollama.chat(
        model="tinyllama",  
        messages=[
            {
                "role": "system", 
                "content": "You are an expert financial advisor providing stock market and investment advice."
            },
            {
                "role": "user", 
                "content": prompt
            }
        ]
    )

    return response.get('message', {}).get('content', 'No response generated.')

st.set_page_config(page_title="Financial Market Advisor", page_icon="📈")
st.title("📈 Financial Market Advisor")
st.write("""
Ask questions about stocks, investing strategies, or market analysis.
Examples: 
- Should I invest in AAPL right now?
- What's a good strategy for dividend investing?
- Explain how to read candlestick patterns
""")


user_input = st.text_area("Your Financial Question", height=150, 
                         placeholder="e.g., What are the key indicators to watch when buying tech stocks?")

if st.button("Get Financial Advice"):
    if user_input:
        with st.spinner('Analyzing your financial question...'):
           
            result = get_financial_advice(user_input)
            

            with st.expander("See Financial Analysis", expanded=True):
                st.markdown(result)
                
            st.warning("""
            **Disclaimer:** This information is generated by AI and should not be considered as financial advice. 
            Always conduct your own research and consult with a licensed financial advisor before making investment decisions.
            Past performance is not indicative of future results.
            """)
    else:
        st.error("Please enter a financial question or query about the stock market.")

with st.sidebar:
    st.header("Configuration")
    model_option = st.selectbox(
        "Select AI Model",
        ("tinyllama", "mistral", "llama2"),
        index=0
    )
    
    st.markdown("---")
    st.markdown("""
    **Sample Questions:**
    - Technical analysis of TSLA stock
    - Best long-term investment strategy
    - How to interpret P/E ratio
    - Risk assessment of crypto investments
    """)